name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  api-tests:
    name: Run API Tests
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run API tests only
      run: dotnet test --filter Category=API

  ui-tests:
    name: Run UI Tests
    runs-on: windows-latest
    needs: api-tests
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run UI tests only
      run: dotnet test --filter Category=UI

    - name: Show test result output
      if: failure()
      run: cat ./TestResults/*.trx || true

  e2e-tests:
    name: Run E2E Tests
    runs-on: windows-latest
    needs: ui-tests
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run UI tests only
      run: dotnet test --filter Category=UI

    - name: Show test result output
      if: failure()
      run: cat ./TestResults/*.trx || true

    - name: Upload Screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Screenshots
        path: MyTests/bin/Debug/net*/Screenshots

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Logs
        path: MyTests/bin/Debug/net*/test-log.txt