name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore automation.sln

      - name: Build solution
        run: dotnet build automation.sln --no-restore --configuration Release

      - name: Run all tests
        run: dotnet test automation.sln --no-build --configuration Release \
          --logger "trx;LogFileName=test-results.trx"

      - name: Publish test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/test-results.trx'

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: MyTests/bin/Debug/net*/Screenshots